-- ===========================================================================
-- E4: Hukuki sayfa TASLAKLARI (mesafeli-satis, iade-degisim, gizlilik, cerez).
--
-- !!! D R A F T — YAYINDAN ÖNCE ZORUNLU !!!
--   1. [FİRMA ÜNVANI]/[ADRES]/[VKN]/[E-POSTA]/[TELEFON] yer tutucularını doldur
--      (Ayarlar > İletişim bilgileriyle tutarlı olsun).
--   2. [POLİTİKA:...] diye işaretlenmiş maddeler işletme kararı ister (iade
--      süreleri, teslim süresi, hijyen kategorileri) — kararlaştır, düzelt.
--   3. Hukuki metin hukuk müşaviri onayından geçmeli — bu bir TASLAK şablondur,
--      hukuki danışmanlık değildir.
--   Sayfalar durum=1 (yayında) yazılır; site henüz canlı olmadığı için sorun yok.
--   Canlı ÖNCESİ bu dosyanın yer tutucusuz halini paneleden (Yönetim > Sayfalar)
--   son kez gözden geçir.
-- ===========================================================================
SET NAMES utf8mb4;

DELETE FROM sayfalar WHERE slug IN ('mesafeli-satis','iade-degisim','gizlilik','cerez');

INSERT INTO sayfalar (slug, baslik, icerik, durum) VALUES
('mesafeli-satis', 'Mesafeli Satış Sözleşmesi',
 '<p><strong>Son güncelleme:</strong> [TARİH]</p><h3>1. Taraflar</h3><p><strong>Satıcı:</strong> [FİRMA ÜNVANI] — [ADRES] — VKN: [VKN] — [E-POSTA] — [TELEFON]<br><strong>Alıcı:</strong> Sitede bayi kaydı üzerinden işlem yapan, sipariş anındaki bilgileriyle kayıtlı müşteri (tüzel kişi / tacir).</p><h3>2. Sözleşmenin Konusu</h3><p>İşbu sözleşme, Alıcının web sitemiz üzerinden toptan (bayi) amaçlı ürün satın almasına ilişkin tarafların hak ve yükümlülüklerini 6502 sayılı Tüketicinin Korunması Hakkında Kanun, Mesafeli Sözleşmeler Yönetmeliği, 6563 sayılı Elektronik Ticaretin Düzenlenmesi Hakkında Kanun ve ilgili mevzuat çerçevesinde belirler.</p><h3>3. Ticari (B2B) Mahiyet Beyanı</h3><p>Bu site toptan (bayi) satış amaçlı işletilir. Alıcı, siparişlerini yeniden satış / ticari amaçla verdiğini, bu nedenle 6502 sayılı Kanunun tüketici korumasına ilişkin hükümlerinin tacir niteliğindeki alıcılar hakkında uygulanmayacağını bildiğini ve kabul eder. Alıcının tüketici sıfatıyla hareket ettiği işlemlerde ilgili mevzuat hükümleri saklıdır.</p><h3>4. Sipariş ve Onay Süreci</h3><p>Alıcı, sepetine eklediği ürünleri minimum sipariş adedi (MOQ) ve adet basamağı koşullarıyla onaylar. Sipariş, ödeme kaydına bağlı olarak işleme alınır; havale/EFT ödemelerinde tutarın hesabımıza ulaşması sonrası sipariş onaylanır. Kart (PayTR) ödemelerinde onay, ödeme kuruluşu bildirimiyle verilir. Fiyatlar, sipariş anında seçilen para birimi ve anlık kur ile kayda geçirilir.</p><h3>5. Teslimat</h3><p>Siparişler, ödeme onayını izleyen [POLİTİKA: ör. 1-3] iş günü içinde anlaşmalı kargo firmasıyla Alıcının belirttiği teslimat adresine gönderilir. Kargo süresi, kargo firmasının sorumluluğundadır; gecikmelerde kargo takip bilgisiyle bilgi verilir.</p><h3>6. Cayma Hakkı ve İade</h3><p>Mesafeli Sözleşmeler Yönetmeliği uyarınca tüketici sıfatındaki alıcılar için cayma süresi 14 gündür; bu hakkın kullanılmasına ve istisnalarına ilişkin koşullar <a href="/sayfa/iade-degisim">İade ve Değişim</a> sayfasında ayrıca düzenlenmiştir. Tacir alıcılar için iade koşulları, aynı sayfada belirtilen ticari iade politikası çerçevesinde uygulanır.</p><h3>7. Ödeme</h3><p>Ödeme; banka havalesi/EFT veya kredi kartı (PayTR altyapısı ile) ile yapılır. Kart bilgileri sitede saklanmaz; ödeme sayfası PayTR güvenlik altyapısı üzerinde yürütülür.</p><h3>8. Uyuşmazlıklar</h3><p>Tüketici sıfatındaki alıcılar için Tüketici Hakem Heyeti ve Tüketici Mahkemesi yetkilidir. Ticari işlemlerde [FİRMA ÜNVANI] merkezinin bulunduğu yer mahkemeleri ve icra daireleri yetkilidir.</p><h3>9. Yürürlük</h3><p>Alıcı, ödeme adımında işbu sözleşmeyi onaylamakla taraf olur.</p>',
 1),
('iade-degisim', 'İade ve Değişim',
 '<p><strong>Son güncelleme:</strong> [TARİH]</p><h3>1. Genel</h3><p>Toptan (B2B) çalışma modelimizde iade ve değişim, aşağıdaki koşullara bağlıdır. İade sürecünü başlatmadan önce lütfen <a href="/iletisim">iletişim</a> sayfasından sipariş numaranızla bize ulaşın.</p><h3>2. Hasarlı / Eksik / Yanlış Teslim</h3><p>Kargo hasarı, eksik veya yanlış ürün gönderimi hâlinde durum, teslim tarihinden itibaren [POLİTİKA: ör. 3] iş günü içinde bildirilmelidir. Kargo hasarlarında hasar tutanağı düzenlenmelidir. Bildirim süresi içinde yapılan başvurularda ürün ücretsiz değiştirilir veya bedeli iade edilir.</p><h3>3. Ayıplı Ürün</h3><p>Ayıplı (kusurlu) ürün bildirimi, teslimden itibaren [POLİTİKA: ör. 14] gün içinde yapılabilir. Ayıp, ürünün tanıtımındaki özelliklerle uyuşmazlık oluşturuyorsa ürün değiştirilir veya bedeli iade edilir.</p><h3>4. İade Edilemeyecek Ürünler</h3><p>Alıcının özel talebiyle kesilen/dikilen/işlenen ürünlerde; hijyen gerektiren kategorilerde [POLİTİKA: ör. iç giyim/çorap]; ve etiketi çıkarılmış, kullanılmış veya ambalajı bozulmuş ürünlerde iade ve değişim yapılmaz.</p><h3>5. İade Süreci</h3><p>Onaylanan iadeler, ürünün bize ulaşmasını izleyen [POLİTİKA: ör. 14] gün içinde iade edilir. Kart ile yapılan ödemelerde iade, aynı kart üzerinden PayTR kanalıyla yapılır; havale ödemelerinde bildirilen banka hesabına aktarılır. Kargo bedeli, ayıp/hasar kaynaklı iadeler dışında iade tutarına dahil değildir.</p><h3>6. Toptan Lot İadeleri</h3><p>Çoklu paket (lot) siparişlerinde kısmi iade [POLİTİKA: kabul edilir / edilmez — koşulu belirt]. Paket içerikleri teslim anında kontrol edilmelidir.</p>',
 1),
('gizlilik', 'Gizlilik ve KVKK',
 '<p><strong>Son güncelleme:</strong> [TARİH]</p><p>İşbu metin, 6698 sayılı Kişisel Verilerin Korunması Kanunu (KVKK) kapsamında veri sorumlusu [FİRMA ÜNVANI] ([ADRES], VKN: [VKN]) tarafından hazırlanmıştır.</p><h3>1. İşlenen Kişisel Veriler</h3><p>Bayi kaydı ve sipariş süreçlerinizde; firma adı, yetkili kişi adı-soyadı, e-posta, telefon, teslimat/fatura adresi, vergi kimlik bilgileri, sipariş ve ödeme kayıtları ile site kullanımına ilişkin IP ve log kayıtları işlenir.</p><h3>2. İşleme Amaçları ve Hukuki Sebep</h3><p>Verileriniz; sözleşmenin kurulması ve ifası (sipariş, fatura, teslimat), talebinize bağlı hizmet sağlanması (feed erişimi), kanundan doğan yükümlülüklerin yerine getirilmesi (Vergi Usul Kanunu kapsamında fatura/saklama), iletişim ve bildirim (sipariş durumu) ile hukuki menfaatlerin korunması amaçlarıyla işlenir.</p><h3>3. Aktarım</h3><p>Verileriniz; kargo firmalarına (teslimat), ödeme kuruluşuna (PayTR — kartla ödeme hâlinde), e-fatura entegratörüne (fatura düzenlenmesi) ve SMS/e-posta hizmet sağlayıcılarına (bildirim), yalnızca ilgili amaçla sınırlı olarak aktarılabilir. Yurt dışına aktarım yapılmamaktadır [POLİTİKA: varsa güncelle].</p><h3>4. Saklama Süresi</h3><p>Veriler, ilgili mevzuatta (başta Vergi Usul Kanunu) öngörülen saklama süreleri boyunca ve işlem amaçları gerektirdiği süre kadar muhafaza edilir; süre sonunda silinir/anonim hâle getirilir.</p><h3>5. Haklarınız</h3><p>KVKK m. 11 uyarınca; verilerinizin işlenip işlenmediğini öğrenme, düzeltilmesini/silinmesini isteme, işlemeye itiraz etme ve zarara uğramanız hâlinde tazminat talep etme haklarına sahipsiniz. Taleplerinizi [E-POSTA] adresine iletebilirsiniz.</p><h3>6. Çerezler</h3><p>Sitede kullanılan çerezlere ilişkin ayrıntılar <a href="/sayfa/cerez">Çerez Politikası</a> sayfasındadır.</p>',
 1),
('cerez', 'Çerez Politikası',
 '<p><strong>Son güncelleme:</strong> [TARİH]</p><h3>1. Zorunlu Çerezler</h3><p>Sitemiz yalnızca işlevsellik için zorunlu iki çerez kullanır: oturum çerezi (<code>teksil_sess</code>) ve güvenlik çerezi (<code>teksil_csrf_cookie</code>, form sahteciliğine karşı koruma). Bunlar tarayıcınızda oturum süresince/belirli bir geçerlilik süresiyle tutulur ve kapatıldıklarında site çalışmaz hâle gelir; açık rıza gerektirmezler.</p><h3>2. Analitik / Üçüncü Taraf Çerezler</h3><p>[POLİTİKA: Analitik ölçüm (ör. Google Analytics) devreye alınırsa, açık rıza yönetimi (çerez onay bandı) eklenmelidir; şu an yalnızca zorunlu çerezler kullanılmaktadır.]</p><h3>3. Çerezleri Yönetme</h3><p>Tarayıcı ayarlarından çerezleri silebilir, üçüncü taraf çerezleri engelleyebilirsiniz. Zorunlu çerezlerin engellenmesi hâlinde oturum açma ve sipariş verme çalışmayabilir.</p>',
 1);
